[package]
name = "photon-standalone"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "examples/winit_hello",
    "examples/simple_window",
    "examples/tray_quit",
    "versoview",
    "tools/servo_prep",
    "tools/servo_locator",
    "tools/tauri_ipc_adapter",
    "tools/tauri_compat_ipc",
    "tools/window_manager",
    "tools/tray_and_notify",
]

[alias]
prep-servo = "run -p servo_prep --"
versoview-tauri-ipc = "run -p versoview --features tauri_ipc --"

[features]
default = []
versoview-runtime = [
    "dep:tokio",
    "dep:tokio-util",
    "dep:bytes",
    "dep:serde",
    "dep:serde_json",
    "dep:bincode",
]
zero_copy = ["dep:nix", "dep:memmap2"]
window_manager = ["dep:window_manager"]

[dependencies]
winit = "0.30.12"
raw-window-handle = "0.6.2"


tokio = { version = "1.47.1", optional = true, features = ["rt-multi-thread", "macros", "sync", "time", "io-std", "io-util", "net", "process"] }
tokio-util = { version = "0.7.16", optional = true, features = ["codec"] }
bytes = { version = "1.10.1", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1.0.145", optional = true }
bincode = { version = "2.0.1", optional = true, features = ["serde"] }

window_manager = { path = "tools/window_manager", optional = true }
[target.'cfg(unix)'.dependencies]
nix = { version = "0.30.1", optional = true, features = ["socket", "uio"] }
memmap2 = { version = "0.9.8", optional = true }

[lints.clippy]
needless_doctest_main = "allow"
